### ISSUE TITLE
Vegas does not pip install on Python 2.7.16

### ISSUE THREAD

**Issue by lukaszbibrzycki** [gplepage/vegas#11]
Complete installation log below. By the way it also fails on anaconda 4.6.11. with the same stderr.
Lukasz

Collecting vegas
  Using cached https://files.pythonhosted.org/packages/1b/1f/4107d2dfbfd37c5e7344b3e2cb0dc50f9c13a8dd93da4869f280a988be89/vegas-3.4.tar.gz
Requirement already satisfied: numpy>=1.7 in /usr/lib64/python3.7/site-packages (from vegas) (1.17.1)
Collecting gvar>=8.0 (from vegas)
  Using cached https://files.pythonhosted.org/packages/8e/95/4a93066de972312d08f0c313003bac02099b16ad488133863a09f6e754f3/gvar-9.2.tar.gz
Installing collected packages: gvar, vegas
  Running setup.py install for gvar: started
    Running setup.py install for gvar: still running...
    Running setup.py install for gvar: still running...
    Running setup.py install for gvar: still running...
    Running setup.py install for gvar: finished with status 'error'
Collecting vegas
  Using cached https://files.pythonhosted.org/packages/1b/1f/4107d2dfbfd37c5e7344b3e2cb0dc50f9c13a8dd93da4869f280a988be89/vegas-3.4.tar.gz
Requirement already satisfied: numpy>=1.7 in /usr/lib64/python3.7/site-packages (from vegas) (1.17.1)
Collecting gvar>=8.0 (from vegas)
  Using cached https://files.pythonhosted.org/packages/8e/95/4a93066de972312d08f0c313003bac02099b16ad488133863a09f6e754f3/gvar-9.2.tar.gz
Installing collected packages: gvar, vegas
  Running setup.py install for gvar: started
    Running setup.py install for gvar: still running...
    Running setup.py install for gvar: still running...
    Running setup.py install for gvar: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lbr2omm5/gvar/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lbr2omm5/gvar/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-yz76nlx9/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-lbr2omm5/gvar/
    Complete output (98 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/gvar
    copying src/gvar/cspline.py -> build/lib.linux-x86_64-3.7/gvar
    copying src/gvar/powerseries.py -> build/lib.linux-x86_64-3.7/gvar
    copying src/gvar/__init__.py -> build/lib.linux-x86_64-3.7/gvar
    copying src/gvar/linalg.py -> build/lib.linux-x86_64-3.7/gvar
    copying src/gvar/ode.py -> build/lib.linux-x86_64-3.7/gvar
    copying src/gvar/root.py -> build/lib.linux-x86_64-3.7/gvar
    copying src/gvar/../gvar.pxd -> build/lib.linux-x86_64-3.7/gvar/..
    copying src/gvar/_svec_smat.pxd -> build/lib.linux-x86_64-3.7/gvar
    copying src/gvar/_gvarcore.pxd -> build/lib.linux-x86_64-3.7/gvar
    running build_ext
    building 'gvar._gvarcore' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    creating build/temp.linux-x86_64-3.7/src/gvar
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -fwrapv -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fPIC -I/usr/lib64/python3.7/site-packages/numpy/core/include -I/usr/include/python3.7m -c src/gvar/_gvarcore.c -o build/temp.linux-x86_64-3.7/src/gvar/_gvarcore.o
    In file included from /usr/lib64/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1830,
                     from /usr/lib64/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /usr/lib64/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from src/gvar/_gvarcore.c:610:
    /usr/lib64/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
       17 | #warning "Using deprecated NumPy API, disable it with " \
          |  ^~~~~~~
    src/gvar/_gvarcore.c: In function ‘__pyx_pw_4gvar_9_gvarcore_4GVar_85deriv’:
    src/gvar/_gvarcore.c:11115:8: warning: ‘__pyx_v_ider’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    11115 |     if (__pyx_t_4) {
          |        ^
    src/gvar/_gvarcore.c:10987:12: note: ‘__pyx_v_ider’ was declared here
    10987 |   npy_intp __pyx_v_ider;
          |            ^~~~~~~~~~~~
    gcc -pthread -shared build/temp.linux-x86_64-3.7/src/gvar/_gvarcore.o -L/usr/lib64 -lpython3.7m -o build/lib.linux-x86_64-3.7/gvar/_gvarcore.cpython-37m-x86_64-linux-gnu.so
    building 'gvar._svec_smat' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -fwrapv -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fPIC -I/usr/lib64/python3.7/site-packages/numpy/core/include -I/usr/include/python3.7m -c src/gvar/_svec_smat.c -o build/temp.linux-x86_64-3.7/src/gvar/_svec_smat.o
    In file included from /usr/lib64/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1830,
                     from /usr/lib64/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /usr/lib64/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from src/gvar/_svec_smat.c:567:
    /usr/lib64/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
       17 | #warning "Using deprecated NumPy API, disable it with " \
          |  ^~~~~~~
    src/gvar/_svec_smat.c: In function ‘__pyx_f_4gvar_10_svec_smat_4smat_append_diag’:
    src/gvar/_svec_smat.c:8093:17: warning: assignment to ‘PyObject *’ {aka ‘struct _object *’} from incompatible pointer type ‘struct __pyx_obj_4gvar_10_svec_smat_svec *’ [-Wincompatible-pointer-types]
     8093 |     *__pyx_t_21 = __pyx_v_new_svec;
          |                 ^
    src/gvar/_svec_smat.c: In function ‘__pyx_f_4gvar_10_svec_smat_4smat_append_diag_m’:
    src/gvar/_svec_smat.c:8850:17: warning: assignment to ‘PyObject *’ {aka ‘struct _object *’} from incompatible pointer type ‘struct __pyx_obj_4gvar_10_svec_smat_svec *’ [-Wincompatible-pointer-types]
     8850 |     *__pyx_t_28 = __pyx_v_new_svec;
          |                 ^
    gcc -pthread -shared build/temp.linux-x86_64-3.7/src/gvar/_svec_smat.o -L/usr/lib64 -lpython3.7m -o build/lib.linux-x86_64-3.7/gvar/_svec_smat.cpython-37m-x86_64-linux-gnu.so
    building 'gvar._utilities' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -fwrapv -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fPIC -I/usr/lib64/python3.7/site-packages/numpy/core/include -I/usr/include/python3.7m -c src/gvar/_utilities.c -o build/temp.linux-x86_64-3.7/src/gvar/_utilities.o
    In file included from /usr/lib64/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1830,
                     from /usr/lib64/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /usr/lib64/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from src/gvar/_utilities.c:610:
    /usr/lib64/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
       17 | #warning "Using deprecated NumPy API, disable it with " \
          |  ^~~~~~~
    src/gvar/_utilities.c: In function ‘__pyx_f_4gvar_10_utilities_gammaQ_cf’:
    src/gvar/_utilities.c:29845:54: warning: ‘__pyx_v_fac’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    29845 |     __pyx_t_6 = PyFloat_FromDouble(fabs((__pyx_v_fac - 1.0))); if (unlikely(!__pyx_t_6)) __PYX_ERR(0, 1517, __pyx_L1_error)
          |                                         ~~~~~~~~~~~~~^~~~~~
    src/gvar/_utilities.c: In function ‘__pyx_pw_4gvar_10_utilities_3SVD_1__init__’:
    src/gvar/_utilities.c:28358:17: warning: ‘__pyx_v_i’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    28358 |     __pyx_t_5 = __Pyx_PyObject_GetSlice(__pyx_v_val, __pyx_v_i, 0, NULL, NULL, NULL, 1, 0, 1); if (unlikely(!__pyx_t_5)) __PYX_ERR(0, 1382, __pyx_L1_error)
          |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/gvar/_utilities.c:26701:14: note: ‘__pyx_v_i’ was declared here
    26701 |   Py_ssize_t __pyx_v_i;
          |              ^~~~~~~~~
    src/gvar/_utilities.c: In function ‘__pyx_pw_4gvar_10_utilities_9deriv’:
    src/gvar/_utilities.c:6984:10: warning: ‘__pyx_v_ider’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     6984 |       if (__pyx_t_2) {
          |          ^
    src/gvar/_utilities.c:6532:12: note: ‘__pyx_v_ider’ was declared here
     6532 |   npy_intp __pyx_v_ider;
          |            ^~~~~~~~~~~~
    gcc -pthread -shared build/temp.linux-x86_64-3.7/src/gvar/_utilities.o -L/usr/lib64 -lpython3.7m -o build/lib.linux-x86_64-3.7/gvar/_utilities.cpython-37m-x86_64-linux-gnu.so
    building 'gvar.dataset' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -fwrapv -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fPIC -I/usr/lib64/python3.7/site-packages/numpy/core/include -I/usr/include/python3.7m -c src/gvar/dataset.c -o build/temp.linux-x86_64-3.7/src/gvar/dataset.o
    In file included from /usr/lib64/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1830,
                     from /usr/lib64/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /usr/lib64/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from src/gvar/dataset.c:610:
    /usr/lib64/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
       17 | #warning "Using deprecated NumPy API, disable it with " \
          |  ^~~~~~~
    gcc -pthread -shared build/temp.linux-x86_64-3.7/src/gvar/dataset.o -L/usr/lib64 -lpython3.7m -o build/lib.linux-x86_64-3.7/gvar/dataset.cpython-37m-x86_64-linux-gnu.so
    building 'gvar._bufferdict' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -fwrapv -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fPIC -I/usr/lib64/python3.7/site-packages/numpy/core/include -I/usr/include/python3.7m -c src/gvar/_bufferdict.c -o build/temp.linux-x86_64-3.7/src/gvar/_bufferdict.o
    gcc -pthread -shared build/temp.linux-x86_64-3.7/src/gvar/_bufferdict.o -L/usr/lib64 -lpython3.7m -o build/lib.linux-x86_64-3.7/gvar/_bufferdict.cpython-37m-x86_64-linux-gnu.so
    running install_lib
    creating /usr/lib64/python3.7/site-packages/gvar
    error: could not create '/usr/lib64/python3.7/site-packages/gvar': Permission denied
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lbr2omm5/gvar/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lbr2omm5/gvar/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-yz76nlx9/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by gplepage** [comment]
The only error I can see here is a permissions error: you are trying to install in /usr/lib64/python3.7/gvar/. Do you have permission to install software there? Also the header on your message says you are trying to install in Python 2.7.16 but the error transcript says you are actually installing in Python 3.7. Are you using the correct version of pip? Using python -m pip instead of pip, with the correct version of python, might work better.

**Comment by gplepage** [comment]
I am closing this issue because it has been nearly 3 weeks without further activity, and I think the issues may be the ones I identified in my previous comment. Please open an new issue if I am wrong.
