### ISSUE TITLE
Inconsistent reporter output

### ISSUE THREAD

**Issue by luckytoilet** [gplepage/vegas#12]
I'm computing an integral by running many iterations over several hours and printing a running output that gets more accurate over time. For my problem, I need 10 digits of precision.

In the first few iterations, all the digits of the result are printed:

itn  5: 0.1017802(84)
all itn's: **0.1017806**(39)

However, after some number of iterations, the result is rounded to 6 digits before printing, thus making it useless for me:

 itn 18795: 0.1017963(83)
 all itn's: **0.101779** +- 6e-08

Expected behavior: more digits in the same format, eg: 0.1017791234(56).

**Comment by gplepage** [comment]
Thanks for pointing this out. It is an issue with the ``gvar`` module, which is used by ``vegas``. Update ``gvar`` to version 10.0.3 and things should work.

I assume you know this but it is usually much, much better to increase ``neval`` than ``nitn`` when looking for high precision. See the discussion under **Precision** in the documentation: https://vegas.readthedocs.io/en/latest/tutorial.html#basic-integrals

I am going to close the issue. Reopen it if you still have problems after updating ``gvar``.
