### ISSUE TITLE
install by pip inside conda environment doesn't work

### ISSUE THREAD

**Issue by mamerchandmedi** [gplepage/vegas#13]
Hello, I can see similar questions have been asked but i couldn't solve it based on their answers. Here is the full log i obtain ater trying pip install vegas inside a conda environment with python3.6.12:

-> pip install vegas
Collecting vegas
  Using cached vegas-3.5.3.tar.gz (1.1 MB)
Requirement already satisfied: numpy>=1.7 in /opt/anaconda3/envs/cosmoT/lib/python3.6/site-packages (from vegas) (1.16.4)
Collecting gvar>=8.0
  Using cached gvar-11.9.1.tar.gz (1.9 MB)
Requirement already satisfied: scipy in /opt/anaconda3/envs/cosmoT/lib/python3.6/site-packages (from gvar>=8.0->vegas) (1.5.4)
Building wheels for collected packages: vegas, gvar
  Building wheel for vegas (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/anaconda3/envs/cosmoT/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4c/p4y9gn057sl8q20k0s5bcmjc0000gn/T/pip-install-_n9w9c08/vegas_304cf61cb1da41c380c9e904c74eef11/setup.py'"'"'; __file__='"'"'/private/var/folders/4c/p4y9gn057sl8q20k0s5bcmjc0000gn/T/pip-install-_n9w9c08/vegas_304cf61cb1da41c380c9e904c74eef11/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/4c/p4y9gn057sl8q20k0s5bcmjc0000gn/T/pip-wheel-kqv0i0vd
       cwd: /private/var/folders/4c/p4y9gn057sl8q20k0s5bcmjc0000gn/T/pip-install-_n9w9c08/vegas_304cf61cb1da41c380c9e904c74eef11/
  Complete output (23 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.6
  creating build/lib.macosx-10.9-x86_64-3.6/vegas
  copying src/vegas/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/vegas
  copying src/vegas/../vegas.pxd -> build/lib.macosx-10.9-x86_64-3.6/vegas/..
  copying src/vegas/_vegas.pxd -> build/lib.macosx-10.9-x86_64-3.6/vegas
  running build_ext
  building 'vegas._vegas' extension
  creating build/temp.macosx-10.9-x86_64-3.6
  creating build/temp.macosx-10.9-x86_64-3.6/src
  creating build/temp.macosx-10.9-x86_64-3.6/src/vegas
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/anaconda3/envs/cosmoT/include -arch x86_64 -I/opt/anaconda3/envs/cosmoT/include -arch x86_64 -I/opt/anaconda3/envs/cosmoT/lib/python3.6/site-packages/numpy/core/include -I/opt/anaconda3/envs/cosmoT/include/python3.6m -c src/vegas/_vegas.c -o build/temp.macosx-10.9-x86_64-3.6/src/vegas/_vegas.o
  dyld: Library not loaded: /usr/local/lib/libmpc.3.dylib
    Referenced from: /usr/local/libexec/gcc/x86_64-apple-darwin17.5.0/8.1.0/cc1
    Reason: image not found
  gcc: internal compiler error: Abort trap: 6 signal terminated program cc1
  Please submit a full bug report,
  with preprocessed source if appropriate.
  See <https://gcc.gnu.org/bugs/> for instructions.
  error: command 'gcc' failed with exit status 4
  ----------------------------------------
  ERROR: Failed building wheel for vegas
  Running setup.py clean for vegas
  Building wheel for gvar (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/anaconda3/envs/cosmoT/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4c/p4y9gn057sl8q20k0s5bcmjc0000gn/T/pip-install-_n9w9c08/gvar_81667170105c449ca2b9f7bd66e9a7c4/setup.py'"'"'; __file__='"'"'/private/var/folders/4c/p4y9gn057sl8q20k0s5bcmjc0000gn/T/pip-install-_n9w9c08/gvar_81667170105c449ca2b9f7bd66e9a7c4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/4c/p4y9gn057sl8q20k0s5bcmjc0000gn/T/pip-wheel-eowtbnn6
       cwd: /private/var/folders/4c/p4y9gn057sl8q20k0s5bcmjc0000gn/T/pip-install-_n9w9c08/gvar_81667170105c449ca2b9f7bd66e9a7c4/
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.6
  creating build/lib.macosx-10.9-x86_64-3.6/gvar
  copying src/gvar/cspline.py -> build/lib.macosx-10.9-x86_64-3.6/gvar
  copying src/gvar/powerseries.py -> build/lib.macosx-10.9-x86_64-3.6/gvar
  copying src/gvar/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/gvar
  copying src/gvar/pade.py -> build/lib.macosx-10.9-x86_64-3.6/gvar
  copying src/gvar/linalg.py -> build/lib.macosx-10.9-x86_64-3.6/gvar
  copying src/gvar/ode.py -> build/lib.macosx-10.9-x86_64-3.6/gvar
  copying src/gvar/root.py -> build/lib.macosx-10.9-x86_64-3.6/gvar
  copying src/gvar/../gvar.pxd -> build/lib.macosx-10.9-x86_64-3.6/gvar/..
  copying src/gvar/_svec_smat.pxd -> build/lib.macosx-10.9-x86_64-3.6/gvar
  copying src/gvar/_gvarcore.pxd -> build/lib.macosx-10.9-x86_64-3.6/gvar
  running build_ext
  building 'gvar._gvarcore' extension
  creating build/temp.macosx-10.9-x86_64-3.6
  creating build/temp.macosx-10.9-x86_64-3.6/src
  creating build/temp.macosx-10.9-x86_64-3.6/src/gvar
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/anaconda3/envs/cosmoT/include -arch x86_64 -I/opt/anaconda3/envs/cosmoT/include -arch x86_64 -I/opt/anaconda3/envs/cosmoT/lib/python3.6/site-packages/numpy/core/include -I/opt/anaconda3/envs/cosmoT/include/python3.6m -c src/gvar/_gvarcore.c -o build/temp.macosx-10.9-x86_64-3.6/src/gvar/_gvarcore.o
  dyld: Library not loaded: /usr/local/lib/libmpc.3.dylib
    Referenced from: /usr/local/libexec/gcc/x86_64-apple-darwin17.5.0/8.1.0/cc1
    Reason: image not found
  gcc: internal compiler error: Abort trap: 6 signal terminated program cc1
  Please submit a full bug report,
  with preprocessed source if appropriate.
  See <https://gcc.gnu.org/bugs/> for instructions.
  error: command 'gcc' failed with exit status 4
  ----------------------------------------
  ERROR: Failed building wheel for gvar
  Running setup.py clean for gvar
Failed to build vegas gvar
Installing collected packages: gvar, vegas
    Running setup.py install for gvar ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/anaconda3/envs/cosmoT/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4c/p4y9gn057sl8q20k0s5bcmjc0000gn/T/pip-install-_n9w9c08/gvar_81667170105c449ca2b9f7bd66e9a7c4/setup.py'"'"'; __file__='"'"'/private/var/folders/4c/p4y9gn057sl8q20k0s5bcmjc0000gn/T/pip-install-_n9w9c08/gvar_81667170105c449ca2b9f7bd66e9a7c4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/4c/p4y9gn057sl8q20k0s5bcmjc0000gn/T/pip-record-xn0mtvmz/install-record.txt --single-version-externally-managed --compile --install-headers /opt/anaconda3/envs/cosmoT/include/python3.6m/gvar
         cwd: /private/var/folders/4c/p4y9gn057sl8q20k0s5bcmjc0000gn/T/pip-install-_n9w9c08/gvar_81667170105c449ca2b9f7bd66e9a7c4/
    Complete output (30 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.6
    creating build/lib.macosx-10.9-x86_64-3.6/gvar
    copying src/gvar/cspline.py -> build/lib.macosx-10.9-x86_64-3.6/gvar
    copying src/gvar/powerseries.py -> build/lib.macosx-10.9-x86_64-3.6/gvar
    copying src/gvar/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/gvar
    copying src/gvar/pade.py -> build/lib.macosx-10.9-x86_64-3.6/gvar
    copying src/gvar/linalg.py -> build/lib.macosx-10.9-x86_64-3.6/gvar
    copying src/gvar/ode.py -> build/lib.macosx-10.9-x86_64-3.6/gvar
    copying src/gvar/root.py -> build/lib.macosx-10.9-x86_64-3.6/gvar
    copying src/gvar/../gvar.pxd -> build/lib.macosx-10.9-x86_64-3.6/gvar/..
    copying src/gvar/_svec_smat.pxd -> build/lib.macosx-10.9-x86_64-3.6/gvar
    copying src/gvar/_gvarcore.pxd -> build/lib.macosx-10.9-x86_64-3.6/gvar
    running build_ext
    building 'gvar._gvarcore' extension
    creating build/temp.macosx-10.9-x86_64-3.6
    creating build/temp.macosx-10.9-x86_64-3.6/src
    creating build/temp.macosx-10.9-x86_64-3.6/src/gvar
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/anaconda3/envs/cosmoT/include -arch x86_64 -I/opt/anaconda3/envs/cosmoT/include -arch x86_64 -I/opt/anaconda3/envs/cosmoT/lib/python3.6/site-packages/numpy/core/include -I/opt/anaconda3/envs/cosmoT/include/python3.6m -c src/gvar/_gvarcore.c -o build/temp.macosx-10.9-x86_64-3.6/src/gvar/_gvarcore.o
    dyld: Library not loaded: /usr/local/lib/libmpc.3.dylib
      Referenced from: /usr/local/libexec/gcc/x86_64-apple-darwin17.5.0/8.1.0/cc1
      Reason: image not found
    gcc: internal compiler error: Abort trap: 6 signal terminated program cc1
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <https://gcc.gnu.org/bugs/> for instructions.
    error: command 'gcc' failed with exit status 4
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/anaconda3/envs/cosmoT/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4c/p4y9gn057sl8q20k0s5bcmjc0000gn/T/pip-install-_n9w9c08/gvar_81667170105c449ca2b9f7bd66e9a7c4/setup.py'"'"'; __file__='"'"'/private/var/folders/4c/p4y9gn057sl8q20k0s5bcmjc0000gn/T/pip-install-_n9w9c08/gvar_81667170105c449ca2b9f7bd66e9a7c4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/4c/p4y9gn057sl8q20k0s5bcmjc0000gn/T/pip-record-xn0mtvmz/install-record.txt --single-version-externally-managed --compile --install-headers /opt/anaconda3/envs/cosmoT/include/python3.6m/gvar Check the logs for full command output.

**Comment by gplepage** [comment]
The problem seems to be that the compiler cannot find the C library ``libmpc.3.dylib``. It is looking in ``/usr/local/lib/``. When I install using an anaconda environment, my compiler is *automatically* directed to look in ``~/opt/anaconda3/envs/[env-name]/lib`` which is where that library lives in an anaconda distribution. Do you have the library in that directory in your environment?

The script ``setup.py`` can be modified to add extra link arguments when using ``pip``. You can, for example, use set ``extra_link_args=["-Ldirectory-name"]`` replacing ``directory-name`` with the full name of the directory where your ``libmpc.3.dylib`` is located. This might help the compiler find it.

My code does not use this library directly. It is probably used by ``numpy`` or ``scipy``.

I regularly install ``vegas`` inside anaconda environments without problems. So we should be able to get your install to work. I use Apple's ``gcc`` (i.e., ``/usr/bin/gcc``), which could be a difference.

**Comment by mamerchandmedi** [comment]
Hi, I am very neophyte on terminal but I know how to use python. 
I typed 
->which gcc 
/usr/local/bin/gcc
this is different than yours....
how can I tell terminal (or pip install) to look in there?

**Comment by mamerchandmedi** [comment]
P.D. I checked the folder ~/opt/anaconda3/envs/[env-name]/lib 
but libmpc.3.dylib is not in there...

**Comment by gplepage** [comment]
This is hard to diagnose without knowing more about your system. Some things to check and questions:

1) While in the conda environment using terminal type ``which pip``. It should say something like ``/opt/anaconda3/envs/cosmoT/bin/pip``. This makes sure that you are using the pip that comes with your python. (I am assuming that ``which python`` gives ``/opt/anaconda3/envs/cosmoT/bin/python``.)

2) See if ``libmpc.3.dylib`` is in ``/opt/anaconda3/envs/cosmoT/lib/``. This is a different directory than the one I suggested earlier (I misread the error messages you posted). 

3) If ``libmpc.3.dylib`` is in the directory mentioned above then try modifying the line in the ``setup.py`` file in the ``vegas`` distribution so that says ``extra_link_args=[]`` to read:

   ```extra_link_args=["-L/opt/anaconda3/envs/cosmoT/lib/"]```

   Try installing again.

4) You might try downloading and installing the Python module ``gvar`` before installing ``vegas``. It is needed by ``vegas`` and might generate the same issues.

By the way, it might be faster to use email rather than working through github. I am happy to do it either way, but if you want to use email respond to me at ``g.p.lepage@cornell.edu``.

**Comment by mamerchandmedi** [comment]
Thank you. I e-mailed you.

**Comment by gplepage** [comment]
This issue was resolved off line. For the benefit of anyone else with a similar issue, the problem was that ``pip`` was using the wrong C compiler. Prefacing the ``pip`` command with ``CC=/usr/bin/clang`` (for MacOS) got ``pip`` to use the correct compiler.

**Comment by yutongo** [comment]
Hello,

I tried the step1-4 and make CC=/usr/bin/clang but still I got the error:
running install
running build
running build_py
copying src/vegas/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/vegas
running build_ext
building 'vegas._vegas' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/yutong/opt/anaconda3/include -arch x86_64 -I/Users/yutong/opt/anaconda3/include -arch x86_64 -I/Users/yutong/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/yutong/opt/anaconda3/include/python3.7m -c src/vegas/_vegas.c -o build/temp.macosx-10.9-x86_64-3.7/src/vegas/_vegas.o
In file included from /usr/local/lib/gcc/x86_64-apple-darwin15.0.0/5.2.0/include-fixed/syslimits.h:7:0,
                 from /usr/local/lib/gcc/x86_64-apple-darwin15.0.0/5.2.0/include-fixed/limits.h:34,
                 from /Users/yutong/opt/anaconda3/include/python3.7m/Python.h:11,
                 from src/vegas/_vegas.c:4:
/usr/local/lib/gcc/x86_64-apple-darwin15.0.0/5.2.0/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1

The gcc version I used is gcc (GCC) 5.2.0.

Any suggestions?

Thank you.




> This is hard to diagnose without knowing more about your system. Some things to check and questions:
> 
> 1. While in the conda environment using terminal type `which pip`. It should say something like `/opt/anaconda3/envs/cosmoT/bin/pip`. This makes sure that you are using the pip that comes with your python. (I am assuming that `which python` gives `/opt/anaconda3/envs/cosmoT/bin/python`.)
> 2. See if `libmpc.3.dylib` is in `/opt/anaconda3/envs/cosmoT/lib/`. This is a different directory than the one I suggested earlier (I misread the error messages you posted).
> 3. If `libmpc.3.dylib` is in the directory mentioned above then try modifying the line in the `setup.py` file in the `vegas` distribution so that says `extra_link_args=[]` to read:
>    `extra_link_args=["-L/opt/anaconda3/envs/cosmoT/lib/"]`
>    Try installing again.
> 4. You might try downloading and installing the Python module `gvar` before installing `vegas`. It is needed by `vegas` and might generate the same issues.
> 
> By the way, it might be faster to use email rather than working through github. I am happy to do it either way, but if you want to use email respond to me at `g.p.lepage@cornell.edu`.
