### ISSUE TITLE
ZeroFloatDivision in AdaptativeMap.adapt

### ISSUE THREAD

**Issue by philastrophist** [gplepage/vegas#17]
Perhaps this is a pathalogical example but I'm trying to integrate a function over a large domain.
I want to integrate many thousands of functions (with different parameters) and sometimes the important area of the function is very small or very large. Therefore, I use the `adapt_to_samples` to give the integrator a reasonable shot at finding that area.

However, I get `ZeroDivisionError: float division` every time for one of these functions (with a small spike)

`vegas.__version__ == 4.0.1`

```
Traceback (most recent call last):
  File "/home/ppzscr/star-forming/integrator.py", line 100, in <module>
    r = integrator.integrate(nadapt=1e5, alpha=0.5)
  File "/home/ppzscr/star-forming/integrator.py", line 84, in integrate
    self.adaptive_map.adapt_to_samples(self._samples, func(self._samples), nitn=nadapt)  # precondition map
  File "_vegas.pyx", line 736, in vegas._vegas.AdaptiveMap.adapt_to_samples
  File "_vegas.pyx", line 555, in vegas._vegas.AdaptiveMap.adapt
ZeroDivisionError: float division

Process finished with exit code 1

```
The entire code is here:

```
from sklearn.mixture import GaussianMixture
import vegas
from astropy.cosmology import Planck15
import numpy as np
from scipy import stats


class Integrator:
    def __init__(self, logm_observed, logm_error, f_observed, f_error, z_observed, z_error,
                 mu, V,
                 logl_range, logm_range,
                 z_range=(0., 1.), zpoints=1000, n_adapt_samples=1000,
                 zdeg=2, cosmo=Planck15, alpha=-0.71):
        self.f_observed = f_observed
        self.f_error = f_error
        self.z_observed = z_observed
        self.z_error = z_error
        self.logm_observed = logm_observed
        self.logm_error = logm_error
        self.mu = mu
        self.V = V
        self.gaussian_component = stats.multivariate_normal(mu, V)
        self.z_range = z_range
        self.alpha = alpha
        _zs = np.linspace(*z_range, num=zpoints)
        _dls = cosmo.luminosity_distance(_zs)
        self.dl_params = np.polyfit(_zs, Planck15.luminosity_distance(_zs), zdeg)
        self.logm_range = logm_range
        self.logl_range = logl_range
        self.adaptive_map = vegas.AdaptiveMap([logm_range, logl_range, z_range])  # uniform map
        self.logm_dist = stats.norm(self.logm_observed, self.logm_error)
        self.f_dist = stats.norm(self.f_observed, self.f_error)
        self.z_dist = stats.norm(self.z_observed, self.z_error)
        self._samples = self.generate_map_samples(n_adapt_samples)

    def dl(self, z):
        return np.polyval(self.dl_params, z)

    def logl_to_f(self, logl, z):
        return np.exp(logl - np.log(4 * np.pi) - (2 * np.log(self.dl(z))) + ((1 + self.alpha) * np.log(1 + z)))

    def f_to_logl(self, f, z):
        return np.log(f * 4 * np.pi) + (np.log(self.dl(z))*2) - ((1 + self.alpha) * np.log(1 + z))

    def invdetjacobian(self, f, z):
        """
        The jacobian for the transform `P(f,z | vL, vz) -> P(log[L], z | vL, vz)` is
        [[1/f, dL/dz],
         [0,       1]]
        1 / abs(determinant) = f
        """
        return f

    def logprob_observed_given_true(self, true_m, true_logl, true_z):
        true_f = self.logl_to_f(true_logl, true_z)
        logl_part = self.f_dist.logpdf(true_f) - np.log(self.invdetjacobian(true_f, true_z))
        z_part = self.z_dist.logpdf(true_z)
        m_part = self.logm_dist.logpdf(true_m)
        return logl_part + z_part + m_part

    def logprob_gaussian_component(self, true_mlogl):
        return self.gaussian_component.logpdf(true_mlogl)

    def integrand(self, x):
        return np.exp(self.logprob_observed_given_true(x[:, 0], x[:, 1], x[:, 2]) +
                      self.logprob_gaussian_component(x[:, :2]))

    def sample_true_given_observed(self, n):
        zs = self.z_dist.rvs(n)
        fs = self.f_dist.rvs(n)
        logms = self.logm_dist.rvs(n)
        logls = self.f_to_logl(fs, zs)
        r = np.stack([logms, logls, zs]).T
        return r[np.isnan(r).all(axis=1)]

    def generate_map_samples(self, n):
        comp_samples = np.concatenate([self.gaussian_component.rvs(n), self.z_dist.rvs((n, 1))], axis=1)
        samples = np.concatenate([self.sample_true_given_observed(n), comp_samples])
        gmm = GaussianMixture(1).fit(samples)
        return np.concatenate([samples, gmm.sample(n)[0]])

    def integrate(self, neval=1e5, nitn=10, nadapt=10, alpha=0.1):
        func = vegas.batchintegrand(self.integrand)
        self.adaptive_map.adapt_to_samples(self._samples, func(self._samples), nitn=nadapt)  # precondition map
        integ = vegas.Integrator(self.adaptive_map, alpha=alpha)
        return integ(func, neval=neval, nitn=nitn)

    def plot_result(self, r):
        import matplotlib.pyplot as plt
        plt.errorbar(np.arange(len(r.itn_results)), *zip(*[(i.mean, i.sdev) for i in r.itn_results]))
        plt.axhspan(r.mean - r.sdev, r.mean + r.sdev, alpha=0.2)

if __name__ == '__main__':
    mu = [11, 20.8]
    cov = np.eye(2) * 0.1
    f, ferr, z, zerr = 0, 1e-4, 0.085, 0.0001
    m, merr = 11, 0.1

    integrator = Integrator(m, merr, f, ferr, z, zerr, mu, cov, [0, 50], [0, 50])
    r = integrator.integrate()
    print('result = %s   Q = %.2f' % (r, r.Q))
    print(r.summary())
```

There are many adaption samples which have a value of 0 but vegas should integrate anyway, right?

**Comment by gplepage** [comment]
Thanks for posting the problem. I see what needs to be fixed. Will try to have a corrected version up by the end of the day.

**Comment by philastrophist** [comment]
Thanks!

**Comment by gplepage** [comment]
I think there are two problems. One is that the function values vanish for all of the samples you give to ``adapt_to_samples``. I will change ``adapt_to_samples`` so it doesn't crash when this happens, but the fix is equivalent to dropping the ``adapt_to_samples`` line in your code. You need some samples where the integrand is nonzero in order for ``adapt_to_samples`` to help.

I tried your code without the ``adapt_to_samples`` line but it again crashes. This time it is because your integrand is returning lots of ``nan``s. I modified your integrand so it returns 0.0 instead of ``nan`` whenever one arises:

    def integrand(self, x):
       ans = np.exp(self.logprob_observed_given_true(x[:, 0], x[:, 1], x[:, 2]) +
                     self.logprob_gaussian_component(x[:, :2]))
       ans[np.isnan(ans)] = 0.0
       return ans

This works but gives exactly 0.0 for the integral, suggesting that ``nan``s are occurring all the time. (I checked and that seems to be true.) The ``nan``s may be related to the following  ``RuntimeWarning``s that I get from running the code:

    /Users/gpl/software/python/vegas/tmp/code.py:42: RuntimeWarning: invalid value encountered in log
    return np.log(f * 4 * np.pi) + (np.log(self.dl(z))*2) - ((1 + self.alpha) * np.log(1 + z))
    
    /Users/gpl/software/python/vegas/tmp/code.py:39: RuntimeWarning: invalid value encountered in log
    return np.exp(logl - np.log(4 * np.pi) - (2 * np.log(self.dl(z))) + ((1 + self.alpha) * np.log(1 + z)))
    
    /Users/gpl/opt/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:897: RuntimeWarning: invalid value encountered in greater_equal
    return (a <= x) & (x <= b)
    
    /Users/gpl/opt/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:897: RuntimeWarning: invalid value encountered in less_equal
    return (a <= x) & (x <= b)

As I say I will post a version of ``vegas`` with an ``adapt_to_samples`` that works when the function values are zero. In the meantime you can drop that line in  your code, but you still need to get rid of the ``nan``s. ``vegas`` doesn't like them (and I am reluctant to build in a check for them since it is easy to do that in the integrand itself).

**Comment by philastrophist** [comment]
That's interesting because I'm not getting nans, I'm simply getting 0s (without your fix). 
But anyway, it seems the problem arises when everything vegas samples is 0. I've adjusted my integral by scaling the log-likelihood and then dividing it out at the end.

But now I'm getting the following message when I integrate (adapting works fine now) and the samples I give it are certainly finite and all above 0. The `func` can be called just fine.

Updated code: https://gist.github.com/philastrophist/619fb7045d760212a06c95f811effb21 

```
  File "/home/ppzscr/star-forming/integrator.py", line 96, in integrate
    return integ(func, neval=neval, nitn=nitn), adjustment
  File "_vegas.pyx", line 1620, in vegas._vegas.Integrator.__call__
  File "_vegas.pyx", line 1424, in random_batch
  File "mtrand.pyx", line 432, in numpy.random.mtrand.RandomState.random
  File "mtrand.pyx", line 423, in numpy.random.mtrand.RandomState.random_sample
  File "_common.pyx", line 270, in numpy.random._common.double_fill
ValueError: negative dimensions are not allowed

Process finished with exit code 1

```

**Comment by gplepage** [comment]
Version 4.0.2 of ``vegas`` fixes the ``ZeroDivisionError``.

I am getting the same error message (about negative dimensions) when I run your new code but it is definitely caused by ``nan``s. The error goes away if replace your ``func`` by:

        def func(x):
            ans = np.exp(self.logintegrand(x) + adjustment)
            ans[np.isnan(ans)] = 0.0
            return ans 

Then the code gives a reasonable result:

    result = 0.000045053(23)   Q = 0.20
    itn   integral        wgt average     chi2/dof        Q
    -------------------------------------------------------
      1   0.00004530(62)  0.00004530(62)      0.00     1.00
      2   0.00004459(18)  0.00004465(17)      1.23     0.27
      3   0.00004509(15)  0.00004489(11)      2.47     0.08
      4   0.00004510(18)  0.000044950(97)     1.94     0.12
      5   0.00004517(11)  0.000045045(73)     2.00     0.09
      6   0.000045108(68) 0.000045079(50)     1.68     0.13
      7   0.000044954(57) 0.000045025(37)     1.85     0.09
      8   0.000045093(51) 0.000045049(30)     1.75     0.09
      9   0.000045052(52) 0.000045050(26)     1.53     0.14
     10   0.000045061(45) 0.000045053(23)     1.37     0.20

I will have later versions of ``vegas`` check for ``nan``s.

**Comment by gplepage** [comment]
I accidentally left out the ``@vegas.batchintegrand`` in my version of func:

    @vegas.batchintegrand
    def func(x):
        ans = np.exp(self.logintegrand(x) + adjustment)
        ans[np.isnan(ans)] = 0.0
        return ans

**Comment by philastrophist** [comment]
Also, I missunderstood you. Yes, there were nans, but the error still happens anyway

**Comment by gplepage** [comment]
The error happens with my version of ``func``?

**Comment by philastrophist** [comment]
Ah right, yes I still missed that line out. damn it.

**Comment by philastrophist** [comment]
Ok if the zerodivision is sorted then this issue is closed! Thanks!
