### ISSUE TITLE
Problem installing vegas

### ISSUE THREAD

**Issue by Gaussian-art** [gplepage/vegas#21]
When I try to install vegas (using Linux Mint 20.2) with 'pip install --no-chache -v vegas' I get the following error:

Using pip 21.2.4 from /home/user/anaconda3/envs/venv/lib/python3.9/site-packages/pip (python 3.9)
Collecting vegas
  Downloading vegas-5.0.1.tar.gz (1.2 MB)
     |████████████████████████████████| 1.2 MB 777 kB/s 
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-3na_mn_a/vegas.egg-info
    writing /tmp/pip-pip-egg-info-3na_mn_a/vegas.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-3na_mn_a/vegas.egg-info/dependency_links.txt
    writing requirements to /tmp/pip-pip-egg-info-3na_mn_a/vegas.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-3na_mn_a/vegas.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-3na_mn_a/vegas.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-3na_mn_a/vegas.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'COPYING'
    warning: no previously-included files found matching 'examples/*.tmp'
    warning: no previously-included files found matching 'examples/*.pyc'
    warning: no previously-included files found matching 'examples/*.so'
    warning: no previously-included files found matching 'examples/*.pyxbldc'
    warning: no previously-included files found matching 'tests/*.pyc'
    warning: no previously-included files matching '*' found under directory 'tests/__pycache__'
    warning: no previously-included files matching '*' found under directory 'doc/source/_build'
    writing manifest file '/tmp/pip-pip-egg-info-3na_mn_a/vegas.egg-info/SOURCES.txt'
Requirement already satisfied: numpy>=1.7 in /home/user/anaconda3/envs/venv/lib/python3.9/site-packages (from vegas) (1.20.3)
Collecting gvar>=8.0
  Downloading gvar-11.9.5.tar.gz (1.8 MB)
     |████████████████████████████████| 1.8 MB 3.3 MB/s 
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-6q8061wj/gvar.egg-info
    writing /tmp/pip-pip-egg-info-6q8061wj/gvar.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-6q8061wj/gvar.egg-info/dependency_links.txt
    writing requirements to /tmp/pip-pip-egg-info-6q8061wj/gvar.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-6q8061wj/gvar.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-6q8061wj/gvar.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-6q8061wj/gvar.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'src/*.pyx'
    warning: no previously-included files found matching 'tests/*.pyc'
    warning: no previously-included files found matching 'examples/*.pyc'
    warning: no previously-included files found matching 'examples/*.tmp'
    warning: no previously-included files matching '*' found under directory 'tests/__pycache__'
    warning: no previously-included files matching '*' found under directory 'doc/source/_build'
    adding license file 'LICENSE.txt'
    writing manifest file '/tmp/pip-pip-egg-info-6q8061wj/gvar.egg-info/SOURCES.txt'
Requirement already satisfied: scipy in /home/user/anaconda3/envs/venv/lib/python3.9/site-packages (from gvar>=8.0->vegas) (1.7.1)
Building wheels for collected packages: vegas, gvar
  Running command /home/user/anaconda3/envs/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ehjvan81/vegas_c55418dba08748359afe0569b33ae1d1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ehjvan81/vegas_c55418dba08748359afe0569b33ae1d1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-38f11hm8
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/vegas
  copying src/vegas/__init__.py -> build/lib.linux-x86_64-3.9/vegas
  copying src/vegas/_version.py -> build/lib.linux-x86_64-3.9/vegas
  copying src/vegas/../vegas.pxd -> build/lib.linux-x86_64-3.9/vegas/..
  copying src/vegas/_vegas.pxd -> build/lib.linux-x86_64-3.9/vegas
  running build_ext
  building 'vegas._vegas' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/src
  creating build/temp.linux-x86_64-3.9/src/vegas
  gcc -pthread -B /home/user/anaconda3/envs/venv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/user/anaconda3/envs/venv/include -I/home/user/anaconda3/envs/venv/include -fPIC -O2 -isystem /home/user/anaconda3/envs/venv/include -fPIC -I/home/user/anaconda3/envs/venv/lib/python3.9/site-packages/numpy/core/include -I/home/user/anaconda3/envs/venv/include/python3.9 -c src/vegas/_vegas.c -o build/temp.linux-x86_64-3.9/src/vegas/_vegas.o
  In file included from /usr/lib/gcc/x86_64-linux-gnu/9/include/syslimits.h:7,
                   from /usr/lib/gcc/x86_64-linux-gnu/9/include/limits.h:34,
                   from /home/user/anaconda3/envs/venv/include/python3.9/Python.h:11,
                   from src/vegas/_vegas.c:6:
  /usr/lib/gcc/x86_64-linux-gnu/9/include/limits.h:194:15: fatal error: limits.h: No such file or directory
    194 | #include_next <limits.h>  /* recurse down to the real one */
        |               ^~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  Building wheel for vegas (setup.py) ... error
  ERROR: Failed building wheel for vegas
  Running setup.py clean for vegas
  Running command /home/user/anaconda3/envs/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ehjvan81/vegas_c55418dba08748359afe0569b33ae1d1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ehjvan81/vegas_c55418dba08748359afe0569b33ae1d1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
  running clean
  removing 'build/temp.linux-x86_64-3.9' (and everything under it)
  removing 'build/lib.linux-x86_64-3.9' (and everything under it)
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.9' does not exist -- can't clean it
  removing 'build'
  Running command /home/user/anaconda3/envs/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ehjvan81/gvar_7d3f51341695464199c96ea68f2fffbe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ehjvan81/gvar_7d3f51341695464199c96ea68f2fffbe/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-7r2uf718
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/gvar
  copying src/gvar/linalg.py -> build/lib.linux-x86_64-3.9/gvar
  copying src/gvar/ode.py -> build/lib.linux-x86_64-3.9/gvar
  copying src/gvar/__init__.py -> build/lib.linux-x86_64-3.9/gvar
  copying src/gvar/pade.py -> build/lib.linux-x86_64-3.9/gvar
  copying src/gvar/cspline.py -> build/lib.linux-x86_64-3.9/gvar
  copying src/gvar/root.py -> build/lib.linux-x86_64-3.9/gvar
  copying src/gvar/powerseries.py -> build/lib.linux-x86_64-3.9/gvar
  copying src/gvar/../gvar.pxd -> build/lib.linux-x86_64-3.9/gvar/..
  copying src/gvar/_svec_smat.pxd -> build/lib.linux-x86_64-3.9/gvar
  copying src/gvar/_gvarcore.pxd -> build/lib.linux-x86_64-3.9/gvar
  running build_ext
  building 'gvar._gvarcore' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/src
  creating build/temp.linux-x86_64-3.9/src/gvar
  gcc -pthread -B /home/user/anaconda3/envs/venv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/user/anaconda3/envs/venv/include -I/home/user/anaconda3/envs/venv/include -fPIC -O2 -isystem /home/user/anaconda3/envs/venv/include -fPIC -I/home/user/anaconda3/envs/venv/lib/python3.9/site-packages/numpy/core/include -I/home/user/anaconda3/envs/venv/include/python3.9 -c src/gvar/_gvarcore.c -o build/temp.linux-x86_64-3.9/src/gvar/_gvarcore.o
  In file included from /usr/lib/gcc/x86_64-linux-gnu/9/include/syslimits.h:7,
                   from /usr/lib/gcc/x86_64-linux-gnu/9/include/limits.h:34,
                   from /home/user/anaconda3/envs/venv/include/python3.9/Python.h:11,
                   from src/gvar/_gvarcore.c:6:
  /usr/lib/gcc/x86_64-linux-gnu/9/include/limits.h:194:15: fatal error: limits.h: No such file or directory
    194 | #include_next <limits.h>  /* recurse down to the real one */
        |               ^~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  Building wheel for gvar (setup.py) ... error
  ERROR: Failed building wheel for gvar
  Running setup.py clean for gvar
  Running command /home/user/anaconda3/envs/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ehjvan81/gvar_7d3f51341695464199c96ea68f2fffbe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ehjvan81/gvar_7d3f51341695464199c96ea68f2fffbe/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
  running clean
  removing 'build/temp.linux-x86_64-3.9' (and everything under it)
  removing 'build/lib.linux-x86_64-3.9' (and everything under it)
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.9' does not exist -- can't clean it
  removing 'build'
Failed to build vegas gvar
Installing collected packages: gvar, vegas
    Running command /home/user/anaconda3/envs/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ehjvan81/gvar_7d3f51341695464199c96ea68f2fffbe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ehjvan81/gvar_7d3f51341695464199c96ea68f2fffbe/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ufmdgasp/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/anaconda3/envs/venv/include/python3.9/gvar
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/gvar
    copying src/gvar/linalg.py -> build/lib.linux-x86_64-3.9/gvar
    copying src/gvar/ode.py -> build/lib.linux-x86_64-3.9/gvar
    copying src/gvar/__init__.py -> build/lib.linux-x86_64-3.9/gvar
    copying src/gvar/pade.py -> build/lib.linux-x86_64-3.9/gvar
    copying src/gvar/cspline.py -> build/lib.linux-x86_64-3.9/gvar
    copying src/gvar/root.py -> build/lib.linux-x86_64-3.9/gvar
    copying src/gvar/powerseries.py -> build/lib.linux-x86_64-3.9/gvar
    copying src/gvar/../gvar.pxd -> build/lib.linux-x86_64-3.9/gvar/..
    copying src/gvar/_svec_smat.pxd -> build/lib.linux-x86_64-3.9/gvar
    copying src/gvar/_gvarcore.pxd -> build/lib.linux-x86_64-3.9/gvar
    running build_ext
    building 'gvar._gvarcore' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/src
    creating build/temp.linux-x86_64-3.9/src/gvar
    gcc -pthread -B /home/user/anaconda3/envs/venv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/user/anaconda3/envs/venv/include -I/home/user/anaconda3/envs/venv/include -fPIC -O2 -isystem /home/user/anaconda3/envs/venv/include -fPIC -I/home/user/anaconda3/envs/venv/lib/python3.9/site-packages/numpy/core/include -I/home/user/anaconda3/envs/venv/include/python3.9 -c src/gvar/_gvarcore.c -o build/temp.linux-x86_64-3.9/src/gvar/_gvarcore.o
    In file included from /usr/lib/gcc/x86_64-linux-gnu/9/include/syslimits.h:7,
                     from /usr/lib/gcc/x86_64-linux-gnu/9/include/limits.h:34,
                     from /home/user/anaconda3/envs/venv/include/python3.9/Python.h:11,
                     from src/gvar/_gvarcore.c:6:
    /usr/lib/gcc/x86_64-linux-gnu/9/include/limits.h:194:15: fatal error: limits.h: No such file or directory
      194 | #include_next <limits.h>  /* recurse down to the real one */
          |               ^~~~~~~~~~
    compilation terminated.
    error: command '/usr/bin/gcc' failed with exit code 1
    Running setup.py install for gvar ... error
ERROR: Command errored out with exit status 1: /home/user/anaconda3/envs/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ehjvan81/gvar_7d3f51341695464199c96ea68f2fffbe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ehjvan81/gvar_7d3f51341695464199c96ea68f2fffbe/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ufmdgasp/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/anaconda3/envs/venv/include/python3.9/gvar Check the logs for full command output.

The only error I understand is the line:
/usr/lib/gcc/x86_64-linux-gnu/9/include/limits.h:194:15: fatal error: limits.h: No such file or directory
But this file does exist in my computer.

**Comment by gplepage** [comment]
I think ``/usr/lib/gcc/x86_64-linux-gnu/9/include/limits.h`` is trying to read in a different ``limits.h`` file somewhere else. You might look at the file and see what it is trying to do. This is probably an issue with your ``gcc`` installation, but I have no experience with Linux Mint 2.0.

**Comment by Gaussian-art** [comment]
Thank you. I think I finally solved the problem.
For future reference;
It seems that it wasn't the /usr/lib/gcc/x86_64-linux-gnu/9/include/limits.h file that was missing but the file /usr/include/limits.h as mentioned by Vladislav in https://stackoverflow.com/questions/56280122/gcc-fatal-error-limits-h-no-such-file-or-directory-on-macos
Just installing the package libc6-dev as mentioned by steeldriver in https://unix.stackexchange.com/questions/504139/installing-python-modules-fail-limits-h-missing solved the problem.
