### ISSUE TITLE
Multiprocessing error

### ISSUE THREAD

**Issue by diegourreamendez** [gplepage/vegas#26]
I am trying to run the example you have in the following link:

https://vegas.readthedocs.io/en/latest/tutorial.html#multiple-processors

![image](https://user-images.githubusercontent.com/64099015/200621942-47157ca0-201b-4bb3-a2b4-2172f9e2adc3.png)

However when executing (Windows/Jupyter lab) I get the following error:

AttributeError: Can't get attribute 'ridge' on <module '__main__' (built-in)>

I'm not sure what's going on. Can you help me, please?

**Comment by gplepage** [comment]
Thanks for the feedback. I don't have access to a Windows machine so this is most helpful.

I need to check a few things out but I wonder if the code runs when launched from the command line (``python ridge.py``) rather than from Windows/Jupyter lab. Have you tried that?

**Comment by gplepage** [comment]
Another thing to try is to put the integrand into a file (say ``ridge.py``) and import it into the script:
```
import vegas
import numpy as np

import ridge

def main():
    integ = vegas.Integrator(4 * [[0, 1]], nproc=8)  # 8 processors
    # adapt
    integ(ridge.ridge, nitn=10, neval=1e4)
    # final results
    result = integ(ridge.ridge, nitn=10, neval=1e4)
    print('result = %s    Q = %.2f' % (result, result.Q))

if __name__ == '__main__':
    main()
```
Again this is to help me diagnose the problem. Thanks.

**Comment by diegourreamendez** [comment]
The last solution works for me. Thank you very much!!!!!
