### ISSUE TITLE
Random number generation on the fly 

### ISSUE THREAD

**Issue by ryanplestid** [gplepage/vegas#28]
We are trying to use VEGAS to sample from a distribution "on the fly" i.e. we want to draw single samples rather than compute a large ensemble of samples. 

We have found that drawing from integrand.random() seems to give highly correlated samples and have traced this back to looping through hypercubes in random_batch(). We think that what is going on is that each hypercube has correlated kinematic variables. A solution that works (but is very slow for large lists and is the current bottleneck in our project) is to cast the iterable that VEGAS produces into a list, and then randomize the list. 

Is there a way to draw a truly random "one off" sample from VEGAS? We had thought about hacking the source code to draw a random hypercube rather than iterating through the list of hypercubes but are worried about biasing our sample if the hypercubes have very different weights. 

Thanks in advance, 

Ryan

**Comment by gplepage** [comment]
It sounds like the hypercubes are playing no role in your application. In that case the easiest thing is to set the maximum number of hypercubes equal to 1, in which case the single hypercube encompasses the entire integration volume. Here is a sample code:
```
import vegas
import numpy as np 

@vegas.rbatchintegrand
def f(x):
    return x[0]**2 * x[1]**3 * 12

def main():
    itg = vegas.Integrator([[-1,1], [0,2]])
    r = itg(f)
    print(r.summary())
    itg.set(max_nhcube=1)     # restrict vegas to a single hypercube
    print(itg.settings())
    for x,w in itg.random():
        print(list(x), w)

main()
```
The output from this is:
```
itn   integral        wgt average     chi2/dof        Q
-------------------------------------------------------
  1   32.00(36)       32.00(36)           0.00     1.00
  2   31.94(17)       31.95(16)           0.02     0.88
  3   31.94(13)       31.94(10)           0.01     0.99
  4   31.86(12)       31.909(77)          0.09     0.96
  5   32.01(10)       31.947(61)          0.24     0.92
  6   32.04(10)       31.973(52)          0.32     0.90
  7   32.024(91)      31.985(45)          0.31     0.93
  8   32.044(85)      31.999(40)          0.31     0.95
  9   31.968(80)      31.992(36)          0.29     0.97
 10   32.039(79)      32.000(33)          0.29     0.98

Integrator Settings:
    1000 (approx) integrand evaluations in each of 10 iterations
    number of:  strata/axis = [1 1]
                increments/axis = [100 100]
                h-cubes = 1  evaluations/h-cube = 1000 (min)
                h-cubes/batch = 10000  processors = 1
    minimize_mem = False
    adapt_to_errors = False
    damping parameters: alpha = 0.5  beta= 0.75
    limits: h-cubes < 1  evaluations/h-cube < 1e+06
    accuracy: relative = 0  absolute accuracy = 0

    axis 0 covers (-1.0, 1.0)
    axis 1 covers (0.0, 2.0)

[-0.5509580572361465, 1.9828682045942714] 0.0011219670389760654
[0.9900711256949882, 1.7915953733297345] 0.0005405478385159034
[-0.9985773788691057, 1.8313661230275833] 0.0005228790690293653
[-0.3722447773761474, 1.3530903086591453] 0.006936976693502574
[-0.7014434166446265, 1.2739678838694584] 0.0024623156725603512
[0.7499137872085245, 1.0881437961322624] 0.003617304236875066
[-0.7693397222827306, 1.1946755230872144] 0.0024168275076028216
[-0.9524058414606622, 0.5264125177704763] 0.012339004346540686
...
```
Note that I get rid of the hypercubes after ``vegas`` has adapted to the function (but before generating samples) because the hypercubes generally help the algorithm adapt.

**Comment by ryanplestid** [comment]
This is very helpful. Thanks!
