### ISSUE TITLE
chi2 property not working when rescaling RAvgArray

### ISSUE THREAD

**Issue by Gaussian-art** [gplepage/vegas#29]
Hi, I've recently updated to vegas 5.4 and I found a problem. I don't know if this is a bug or if I'm doing something the wrong way, but after getting the result of an integral and rescaling it, the attribute _rescale is not defined and therefore the _chi2 method doesn't work.

The problem is the following:
```python
import vegas  # vegas 5.4

def f(x):
    return x

integ = vegas.Integrator([[0, 1]])
result = integ(f)
rescaled_result = 2 * result

result.chi2  # This works fine
rescaled_result.chi2  # This raises an AttributeError: 'RAvgArray' object has no attribute '_rescale'
```

I've checked, and the problem is new to version 5.4 (at least, I cannot reproduce it with vegas 5.3). Also, from the source code, I guess the same problem will probably arise for RAvg and RAvgDict objects, but I didn't check it.

As I've said, I don't know if this is a bug or simply that I am not supposed to multiply RAvgArray objects by scalars.

**Comment by gplepage** [comment]
I am surprised ``rescaled_result.chi2`` used to work. I don't think it did for ``RAvg`` results. ``RAvg`` and ``RAvgArray`` are designed to give the expected results when used in arithmetic  expressions but it is fairly complicated to propagate the auxiliary variables like ``chi2`` through such operations (and not totally clear it is desirable). I can probably get it to work again for ``RAvgArray`` but it will be an unsupported feature (ie, it might disappear in the future).

**Comment by Gaussian-art** [comment]
Thank you @gplepage for the response.

> I can probably get it to work again for RAvgArray but it will be an unsupported feature (ie, it might disappear in the future).

Well, if it is an unsupported feature, there is no necessity of fixing it. I was simply computing the Q value for the integral (which needs the chi2) after the rescaling because it was simpler, but I can get the Q value before the scaling instead.

Thank you
