### ISSUE TITLE
Problem in installing with pip

### ISSUE THREAD

**Issue by matteotagliazucchi** [gplepage/vegas#31]
Hi, I'm trying to install `vegas` with `pip` but I have some issues.

I attach the full output in a pdf file: [output.pdf](https://github.com/gplepage/vegas/files/10852114/output.pdf).
I think the error is: 
```
error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
```
and then `ERROR: Failed building wheel for vegas`.
I get also the error:

```
x86_64-linux-gnu-gcc: fatal error: cannot execute ‘as’: execvp: No such file or directory
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1 
```

Can someone help me?

Same errors occur if I try to install `gvar` only.

Thank you

**Comment by matteotagliazucchi** [comment]
Thank you for your answer!


> From your output the error seems to be: `cannot execute ‘as’: execvp: No such file ...`. This sounds like a problem with the compiler setup. I believe `as` is the GNU assembler. It seems that gcc can't find it. Looking online I see that someone points out that `as` is part of the `binutils` package. Is it installed?

It was not installed. So I installed it and run again `pip install vegas`. Unfortunately, same error as before.



> It is possible that the problem could be fixed by rebuilding the .c files using cython on your machine. To do this, download the source code from https://github.com/gplepage/vegas and modify the `setup.py` file so that `USE_CYTHON = True`. Then rebuild from the source: `pip install . --user` while sitting in the top directory. (Alternatively try `make rebuild` in the top directory, which uses a makefile to rebuild the .c files, and compile and install the module.) This would have to be done with `gvar` as well, which you might focus on initially.

I try this procedure on `gvar` first. I simply changed line 28 in ` USE_CYTHON = True` so that this flag is always True.
I then run `pip install . `from top directory (without the `--user` specification since I'm in a virtualenv and I got the error `ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.`) Unfortunately, same problem as before (both with `vegas` and `gvar`.

**Comment by gplepage** [comment]
This still sounds like a problem with the compiler setup or your linux ``PATH`` variable or ? 

Is ``as`` actually installed somewhere on your computer? In my system (MacOS unix), it is in ``/usr/bin/as`` but since I am using an Anaconda installation for Python Cython might be using ``~/opt/anaconda3/bin/as`` which is also present. Both ``/usr/bin`` and ``~/opt/anaconda3/bin`` are in my ``PATH``.

What versions of Python and Cython are you using?

**Comment by matteotagliazucchi** [comment]
Ok quick update: I had to remove and install again `binutils`.
Then everything worked! 

Actually, my laptop is so messy that I had to install other build files with `sudo apt-get install python3 python-dev python3-dev      build-essential libssl-dev libffi-dev      libxml2-dev libxslt1-dev zlib1g-dev`.

Thank you and sorry for opening this stupid issue.

**Comment by gplepage** [comment]
That's great. 

Happy to help (or try to).
