### ISSUE TITLE
Inconsistency with multiple integrands

### ISSUE THREAD

**Issue by jjegg01** [gplepage/vegas#37]
Hi,

a colleague and I noticed some odd behavior when integrating multiple integrands simultaneously and we are not quite sure if that behavior is intended.

Minimum example for reproduction:
```python
import numpy as np
from numpy import sin,cos
import vegas

def f(x):
    # Three integrands (a,c,e) are zero, the other ones differ greatly in scale
    return {
        "a": np.sum(x)*0,
        "b": np.sum(x)*1e-8,
        "c": np.sum(x)*0,
        "d": 1e-8*(sin(5*np.sum(x))+1),
        "e": np.sum(x)*0,
        "f": 1e-8*(cos(20*np.sum(x))+1)
    }

integ = vegas.Integrator(4 * [[0, 1]])
training = integ(f, nitn=10, neval=2000)
result = integ(f, nitn=10, neval=10000)
print(result.summary())
for label in ['a','b','c','d','e','f']:
    print(f"{label}) {result[label]}")
```
We would expect that the integration of the `a`, `c` and `e` integrands result in the same value (zero). However, they do not:
```
[...]/test.py:19: RuntimeWarning: divide by zero encountered in scalar divide
  print(result.summary())
itn   integral        wgt average     chi2/dof        Q
-------------------------------------------------------
  1   0 ± 0           0 ± 0               0.00     1.00
  2   0 ± 0           0 ± 0                inf      nan
  3   0 ± 0           0 ± 0               0.47     0.71
  4   0 ± 0           0 ± 0               0.67     0.68
  5   0 ± 0           0 ± 0               0.48     0.89
  6   0 ± 0           0 ± 0               0.41     0.96
  7   0 ± 0           0 ± 0               0.47     0.96
  8   0 ± 0           0 ± 0               0.72     0.79
  9   0 ± 0           0 ± 0               0.85     0.65
 10   0 ± 0           0 ± 0               0.78     0.77

a) 0 ± 0
b) 1.99933(34)e-08
c) 3.3459(75)e-15
d) 9.976(11)e-09
e) 0 ± 0
f) 9.987(24)e-09
```
This issue seems to be somewhat similar to https://github.com/gplepage/vegas/issues/27 , but here the integration is actually inconsistent across the different integrands. Interestingly, the problem only appears if the non-zero integrands are distinct from one another. Using a list instead of a dictionary to separate the integrands shows the same behavior.

Any idea what is going on here?

**Comment by gplepage** [comment]
The problem has to do with how `vegas` combines results from different iterations. By default this is done using a weighted average, where results from a given iteration are weighted by the inverse of the covariance matrix. Your covariance matrix doesn't have an inverse because `a, c, e` have zero variance. 

As discussed in the `vegas` tutorial on *Calculating Distributions* (see https://vegas.readthedocs.io/en/latest/tutorial.html#calculating-distributions), a general rule of thumb is that when you get these kinds of inconsistencies you should turn adaptation off when computing your final results (but not when training, obviously). So in your code example, I would change `result=...` to 
```
result = integ(f, nitn=10, neval=10000, adapt=False)
```
The output is then more plausible:
```
itn   integral        average         chi2/dof        Q
-------------------------------------------------------
  1   0 ± 0           0 ± 0               0.00     1.00
  2   0 ± 0           0 ± 0               0.46     0.71
  3   0 ± 0           0 ± 0               0.60     0.73
  4   0 ± 0           0 ± 0               0.66     0.75
  5   0 ± 0           0 ± 0               0.61     0.84
  6   0 ± 0           0 ± 0               0.61     0.87
  7   0 ± 0           0 ± 0               0.76     0.75
  8   0 ± 0           0 ± 0               1.00     0.46
  9   0 ± 0           0 ± 0               0.96     0.51
 10   0 ± 0           0 ± 0               0.86     0.67

a) 0 ± 0
b) 1.99948(35)e-08
c) 0 ± 0
d) 9.994(12)e-09
e) 0 ± 0
f) 9.981(24)e-09
```

I usually turn off adaptation in this way when calculating multiple integrals simultaneously, to guarantee that such problems won't bite me.

**Comment by gplepage** [comment]
I should have commented on the relation to the earlier issue (#27). I don't think there is a problem (or at least not the problem above) if the integrands for `a, c, e` returned exactly `1e-100` (or any other nonzero number). There is a particular problem with returning exactly zero, as then the ratio of scales between the different integrands is infinite.

I would still advocate for using `adapt=False` for this case, as above, however.

**Comment by jjegg01** [comment]
Thank you very much for the fast response!

The problem when integrating zero was mostly a curiosity we noticed when setting one integrand in a larger program to zero for debugging purposes. Since using a small but nonzero number for `a`, `c` and `e` also gives consistent results, this was probably not a problem for the runs with actual (nonzero) data anyways. Still, turning off adaptation like you suggested does seem like the most robust solution here. Thank you again for the advice.
