### ISSUE TITLE
Vegas installation problem in macOS

### ISSUE THREAD

**Issue by sougataganguly** [gplepage/vegas#38]
Hi,

Recently, I am going to install vegas in macOS and I got the following error (screenshot is also attached).

error: invalid-pyproject-build-system-requires

× Can not process gvar>=13.0.1 from https://files.pythonhosted.org/packages/37/62/3ae87411825d77f816baf94df520911b9d7b6d9aac33331902044f6c89b2/gvar-13.1.1.tar.gz (from vegas==6.1.3)
╰─> This package has an invalid `build-system.requires` key in pyproject.toml.
    It contains an invalid requirement: "numpy>='2.0'"

note: This is an issue with the package mentioned above, not pip.
hint: See PEP 518 for the detailed specification.
make: *** [install] Error 1

Any help in resolving this issue will be greatly appreciated.

Thank you.

<img width="1503" alt="Screenshot 2024-11-23 at 11 59 29 PM" src="https://github.com/user-attachments/assets/18aa0f31-a9e5-4686-8e35-57e56873135a">

**Comment by gplepage** [comment]
As I said, the problem was with the gvar module (v 13.1.1). I just uploaded a new version (v 13.1.2) of gvar which fixes the problem. 

So your install of vegas should work now. Contact me if it doesn’t.

Peter

**Comment by sougataganguly** [comment]
Hi,

Thanks a lot. It worked.

Thank you.

**Comment by gplepage** [comment]
Thanks for reporting the issue.
