### ISSUE TITLE
Can't integrate the interpolation function

### ISSUE THREAD

**Issue by oldnewsmomomo** [gplepage/vegas#4]
Hi,

I'm trying to make a code to use vegas batch to integrate the function of interpolation.

Below is my code:
pinterpolation11 = interpolate.RegularGridInterpolator((list1,list2,list3,list4,list5),ptable11,'linear',fill_value=None)

 @vegas.batchintegrand
    def f(x):
        aaaa=pinterpolation11([[r*np.cos(x[:,0].T),r*np.sin(x[:,0].T),x[:,1].T,x[:,2].T,x[:,3].T]])
        return aaaa
    integ = vegas.Integrator([[0.0,2*pi],[0.0,zf],[-3.0*CapitalDelta,3.0*CapitalDelta],[0.1*v0star,2.9*v0star]], nhcube_batch=1000)
    result = integ(f, nitn=10, neval=1000)
    a1=result.mean
    print(result.summary())
    print('result = %s    Q = %.2f' % (result, result.Q))

But it doesn't work, the error information is:
ValueError: The requested sample points xi have dimension 5, but this RegularGridInterpolator has dimension 5

I guess the reason is interpolation function is already an tuple operation function.

Below is an example, the augment is tuple and it returns tuple.
aaa=pinterpolation11([[0.1,0.1,1,CapitalDelta*1,2*v0star],[0.1,0.1,0.7,CapitalDelta*1,2*v0star],[0.12,0.1,0.7,CapitalDelta*1.1,2.1*v0star],[0.1,0.1,1.2,CapitalDelta*1,2*v0star]])

How should I solve this problem?

Thank you very much!
XIn

**Comment by gplepage** [comment]
The error message is coming from RegularGridInterpolator, not from vegas. I don't think you are using RegularGridInterpolator correctly. I suspect the argument to pinterpolation11 has the wrong shape: you might try numpy.array([rnp.cos(x[:,0]),rnp.sin(x[:,0]),x[:,1],x[:,2],x[:,3]]).T. 

I do not use RegularGridInterpolator myself and so cannot give you much advice about it. Also there are a lot of typos and undefined variables in your example, so I could easily be misunderstanding it.

**Comment by oldnewsmomomo** [comment]
It works. Thank you very much!

Xin
