### ISSUE TITLE
Variable type mismatch in Windows?

### ISSUE THREAD

**Issue by kevinea42** [gplepage/vegas#6]
On a Windows machine, when I run the example code:
```
import vegas
import math

def f(x):
    dx2 = 0
    for d in range(4):
        dx2 += (x[d] - 0.5) ** 2
    return math.exp(-dx2 * 100.) * 1013.2118364296088

integ = vegas.Integrator([[-1, 1], [0, 1], [0, 1], [0, 1]])

result = integ(f, nitn=10, neval=1000)
print(result.summary())
print('result = %s    Q = %.2f' % (result, result.Q))
```
I get an error message:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-49a6843f4c3f> in <module>()
     10 integ = vegas.Integrator([[-1, 1], [0, 1], [0, 1], [0, 1]])
     11 
---> 12 result = integ(f, nitn=10, neval=1000)
     13 print(result.summary())
     14 print('result = %s    Q = %.2f' % (result, result.Q))

src/vegas/_vegas.pyx in random_batch (src/vegas/_vegas.c:21017)()

ValueError: Buffer dtype mismatch, expected 'int_t' but got 'long long'
```
I know that gvar had a similar issue at one time, so I tried rolling back gvar to version 8.0, but that didn't help.

**Comment by gplepage** [comment]
Thanks. I think I know what is wrong and will post an update later today or tomorrow. If you have the source code and don't want to wait, change the numpy.int_t in line 1365 of file _vegas.pyx (in src/vegas) to numpy.intp_t. That should fix it.

**Comment by gplepage** [comment]
Try the new version (v3.3.1) that I just uploaded here and on pypi.

**Comment by kevinea42** [comment]
Thank you!

Sent from my iPhone

On Apr 18, 2017, at 6:50 AM, Peter Lepage <notifications@github.com<mailto:notifications@github.com>> wrote:


Try the new version (v3.3.1) that I just uploaded here and on pypi.
