### ISSUE TITLE
Installation does not seem to work

### ISSUE THREAD

**Issue by ediazm** [gplepage/vegas#8]
Tried to install in mac with the four options: make install, python install . and python install --user

None worked. Also modified, setup file to: USE_CYTHON = True # True

Got:
-> Failed building wheel for vegas
-> Failed building wheel for gvar

**Comment by gplepage** [comment]
Thanks for reporting the problem. 

I need more information. It would help if you tried installing ``gvar`` first, using

    pip install gvar --no-cache-dir -v

If that fails, as I expect it will, send me the output (there should be a lot). If ``gvar`` installs, try the same thing for ``vegas``:

    pip install vegas --no-cache-dir -v

It would also be useful to know which versions of ``Python``, ``numpy``, and ``cython`` are installed on your machine.

Thanks again.

**Comment by ediazm** [comment]
As you mentioned there was an "incompatibility between Python and the compiler (gcc)

I solved the issue by re-installing: 
-> brew install python
this threw an error which was fixed by:
-> sudo mkdir /usr/local/Frameworks
-> sudo chown $(whoami):admin /usr/local/Frameworks
then
-> xcode-select --install
finally running
-> pip install .

Thank you very much for your assistance.
