### ISSUE TITLE
Casts complex values to real

### ISSUE THREAD

**Issue by e-eight** [gplepage/vegas#9]
Hi,

If I try to integrate a complex function such as `f(x) = (1+i)x` then I get a `ComplexWarning: Casting complex values to real discards the imaginary part`. This gives a completely wrong answer. 
Is it possible to use a complex integrand without casting it to real?

Thanks.

**Comment by gplepage** [comment]
``vegas`` does not directly support complex-valued integrands directly. It is usually easy, however, to split a complex integrand result into its real and imaginary parts, and present them to ``vegas`` as two simultaneous integrands: e.g.,
```
import vegas

def f(x):
    ans = (1 + 1j * x[0]) * x[0]
    return [ans.real, ans.imag]

integ = vegas.Integrator([[0,1]])
z = integ(f)
print('real =', z[0], '  imag =', z[1])
```
This produces the following output:
```
real = 0.500017(19)   imag= 0.333341(14)
```

It would take a fair bit of work to make ``vegas`` work with complex numbers directly, though it is on my todo list as a possible project someday.

**Comment by e-eight** [comment]
Good to know it is on you todo list. In the meanwhile I shall try your suggestion. Thanks for the quick reply.

**Comment by gplepage** [comment]
I am closing this issue because it is more a feature request than an issue.
